<?php
class Backquery_model extends CI_Model {

    public function addforecast($usr=0, $day=0) 
    {
		$this->EXP = $this->load->database('explanner_db', true);

		//echo $usr; exit;


		$sqlLoad = "
			SELECT 

			*

			FROM
			(
			SELECT
			 TO_CHAR(SYSDATE-$day, 'YYYY-MM-DD') AS DT
			,'1:Firm' AS TYP
			,TR.CUST_CD AS CUST_CD
			,MC.CUST_ANAME AS CUST_NAME
			,TR.CUST_ITEM_CD AS CUST_ITEM_CD
			,TR.ITEM_CD AS ITEM_CD
			,MI.ITEM_NAME AS ITEM_NAME
			,MP.MODEL AS MODEL
			,TR.CUST_ODR_NO AS PONo
			,TO_CHAR(TR.SHIP_PLAN_DATE,'YYYY-MM-DD') AS SHIP_PLAN_DATE
			--,TO_CHAR(TR.DESINATED_DLV_DATE,'YYYY/MM/DD HH24:MI') AS DELIVERY
			,TO_CHAR(TR.DESINATED_DLV_DATE,'YYYY-MM-DD') AS DELIVERY_DATE
			,TO_CHAR(TR.DESINATED_DLV_DATE, 'HH24:MI:SS')   AS DELIVERY_TIME
			,TR.SHIP_REMARKS AS SHIP_NOTE
			,TR.ODR_QTY AS QTY
			,TR.TOTAL_SHIP_QTY AS SHIP_QTY
			,TO_CHAR(TR.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
			,TO_CHAR(TR.RECEIVE_DATE,'YYYY-MM-DD') AS RECEIVE_DATE
			,CASE WHEN ( TO_DATE(TO_CHAR(TR.DESINATED_DLV_DATE ,'YYYY/MM/DD'),'YYYY/MM/DD') - TO_DATE(TO_CHAR(TR.SHIP_PLAN_DATE,'YYYY/MM/DD'),'YYYY/MM/DD') ) > 7 THEN TO_CHAR(TR.SHIP_PLAN_DATE,'MM') ELSE TO_CHAR(TR.DESINATED_DLV_DATE,'MM') END M
			,( TO_DATE(TO_CHAR(TR.DESINATED_DLV_DATE ,'YYYY/MM/DD'),'YYYY/MM/DD') - TO_DATE(TO_CHAR(TR.SHIP_PLAN_DATE,'YYYY/MM/DD'),'YYYY/MM/DD') ) T


			FROM
			 T_ODR TR
			,M_ITEM MI
			,M_CUST MC
			,M_PLANT_ITEM MP
			WHERE
			    TR.ITEM_CD = MI.ITEM_CD(+)
			AND TR.COMPANY_CD = MC.COMPANY_CD(+)
			AND TR.CUST_CD = MC.CUST_CD(+)
			AND TR.ITEM_CD = MP.ITEM_CD(+)
			AND TR.DESINATED_DLV_DATE >= TRUNC(ADD_MONTHS(SYSDATE,-1),'MM') AND TR.DESINATED_DLV_DATE <= LAST_DAY(ADD_MONTHS(SYSDATE,4))
			AND TR.DEL_FLG = 0
			AND TR.ODR_CMPLT_FLG = 1

			UNION ALL

			SELECT
			 TO_CHAR(SYSDATE-$day, 'YYYY-MM-DD') AS DT
			,CASE WHEN TW.UNITE_ODR_TYP = 1 THEN '1:Firm'
			      WHEN TU.EDI_DATA_TYP = 2 THEN  '2:Daily forecast'
			      WHEN TU.EDI_DATA_TYP = 10 THEN '10:Total forecast' END AS TYP
			,TW.CUST_CD AS CUST_CD
			,MC.CUST_ANAME AS CUST_NAME
			,TW.CUST_ITEM_CD AS CUST_ITEM_CD
			,TW.ITEM_CD AS ITEM_CD
			,MI.ITEM_NAME AS ITEM_NAME
			,MP.MODEL AS MODEL
			,TR.CUST_ODR_NO AS PONo
			,TO_CHAR(TW.SHIP_PLAN_DATE,'YYYY-MM-DD') AS SHIP_PLAN_DATE
			--,TO_CHAR(TW.DESINATED_DLV_DATE,'YYYY/MM/DD HH24:MI') AS DELIVERY
			,TO_CHAR(TW.DESINATED_DLV_DATE,'YYYY-MM-DD') AS DELIVERY_DATE
			,TO_CHAR(TW.DESINATED_DLV_DATE, 'HH24:MI:SS')   AS DELIVERY_TIME
			,TR.SHIP_REMARKS AS SHIP_NOTE
			,TW.QTY AS QTY
			,0 AS SHIP_QTY
			,TO_CHAR(TW.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
			,TO_CHAR(TW.CREATED_DATE,'YYYY-MM-DD') AS RECEIVE_DATE
			,CASE WHEN ( TO_DATE(TO_CHAR(TW.DESINATED_DLV_DATE ,'YYYY/MM/DD'),'YYYY/MM/DD') - TO_DATE(TO_CHAR(TW.SHIP_PLAN_DATE,'YYYY/MM/DD'),'YYYY/MM/DD') ) > 7 THEN TO_CHAR(TW.SHIP_PLAN_DATE,'MM') ELSE TO_CHAR(TW.DESINATED_DLV_DATE,'MM') END M
			,( TO_DATE(TO_CHAR(TW.DESINATED_DLV_DATE ,'YYYY/MM/DD'),'YYYY/MM/DD') - TO_DATE(TO_CHAR(TW.SHIP_PLAN_DATE,'YYYY/MM/DD'),'YYYY/MM/DD') ) T
			FROM
			 T_UNITE_ODR_WORK TW
			,M_ITEM MI
			,M_CUST MC
			,M_PLANT_ITEM MP
			,T_ODR TR
			,T_UNCNFM_ODR TU
			WHERE
			    TW.ITEM_CD = MI.ITEM_CD(+)
			AND TW.COMPANY_CD = MC.COMPANY_CD(+)
			AND TW.CUST_CD = MC.CUST_CD(+)
			AND TW.PLANT_CD = MP.PLANT_CD(+)
			AND TW.ITEM_CD = MP.ITEM_CD(+)
			AND TW.ODR_DEPOT_CTL_NO = TR.ODR_CTL_NO(+)
			AND TW.ODR_DEPOT_CTL_NO = TU.UNCNFM_ODR_CTL_NO(+)
			AND TW.DESINATED_DLV_DATE >= TRUNC(ADD_MONTHS(SYSDATE,-1),'MM') AND TW.DESINATED_DLV_DATE <= LAST_DAY(ADD_MONTHS(SYSDATE,4))
			ORDER BY
			 DELIVERY_DATE
			,CUST_CD
			,ITEM_CD
			) B

			WHERE
			   B.DELIVERY_DATE BETWEEN TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE,$usr),'MM'),'YYYY-MM-DD') AND TO_CHAR(LAST_DAY(ADD_MONTHS(SYSDATE,$usr)),'YYYY-MM-DD')
			--AND B.CUST_CD = 'D20113'
			 ORDER BY B.SHIP_PLAN_DATE

						";
		$exc = $this->EXP->query($sqlLoad);
		$rec = $exc->result_array();
		$sel = $rec;



		return $sel;


    }



}
?>
